language: php
install:
    composer install
php:
  - 7.2

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)